name: Waka Readme

on:
  schedule:
    # Runs daily at 12:30 AM IST (Adjust the time in UTC as needed)
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: mihirWeb/waka-readme-stats
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
